### PR TITLE
Extractive QA: Handle multiple documents correctly

### PR DESCRIPTION
**Pull request by georgwiese**
#242 

Summary of changes:
- Changed the default parameter for `doc_ids` in the `Answer` constructor to 0.
- Added an `assert` to check the correct `Answer.span` format when `Answer` is constructed.
- Renamed `token_char_offsets` Port to `token_offsets` and added document indices in addition to character indices.
- Changes `prepare_data` to return correct token.
- Refactored Extractive QA Output module and adjusted it to map model predictions back to the correct document index.
- Removed `notebook_source.py`.

### CODE REVIEW

**Comment by riedelcastro** [comment]
What is the status of this?

**Comment by dirkweissenborn** [comment]
@riedelcastro still open, needs a rebase on the master because a lot has changed

**Comment by georgwiese** [comment]
I started resolving the merge conflicts, hope I'll have time to finish it
tomorrow.

**Comment by georgwiese** [comment]
Status update: I merged in the most recent master, but that introduced a few bugs that I need to fix tomorrow.

**Comment by dirkweissenborn** [comment]
@georgwiese is this ready for merge?

**Comment by georgwiese** [comment]
I wanna go through the diff once more to make sure nothing broke during merging. I'm doing it now. Sorry for the delay, there have been a few unplanned incidents related to me being in a desert right now...

**Pull request merged**
